# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            LAFAC
tagline:          'Desenvolvimento de instrumentação eletrônica inteligente e estudo teórico e prático das redes neurais e artificiais.'
description:      'Desenvolvimento de instrumentação eletrônica inteligente e estudo teórico e prático das redes neurais e artificiais.'
url:              http://lafac.github.io/
baseurl:          https://github.com/Lafac.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:          https://github.com/Lafac
