# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            LAFAC
tagline:          'Desenvolvimento de instrumentação eletrônica inteligente e estudo teórico e prático das redes neurais e artificiais.'
description:      'Lab. de Física Aplicada e Computacional (LAFAC/ZAB)'
url:              http://lafac.github.io/
baseurl:          /
root:             /octo-5         
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:          https://github.com/Lafac
